import {ChevronRight, Focus, LocateFixed, Maximize2, Minimize2, Monitor, Moon, PanelLeft, Pin, PinOff, RefreshCw, Search, Sun, X, ZoomIn, ZoomOut} from 'lucide';

type AnyRecord = Record<string, any>;
type IconNode = Array<readonly [string, Record<string,string|number|undefined>]>;
type LayoutNode = {id:string;x?:number;y?:number;width?:number;height?:number;children?:LayoutNode[];edges?:LayoutEdge[]};
type LayoutEdge = {id:string;sources:string[];targets:string[];sections?:Array<{startPoint:{x:number;y:number};bendPoints?:Array<{x:number;y:number}>;endPoint:{x:number;y:number}}>};

const SVG='http://www.w3.org/2000/svg';
const $=<T extends Element=HTMLElement>(id:string)=>document.getElementById(id) as unknown as T;
const svg=(tag:string,attrs:Record<string,string|number|undefined>={})=>{const node=document.createElementNS(SVG,tag);Object.entries(attrs).forEach(([k,v])=>{if(v!==undefined)node.setAttribute(k,String(v))});return node};
const dom=(tag:string,className='',text='')=>{const node=document.createElement(tag);node.className=className;if(text)node.textContent=text;return node};

function icon(node:IconNode,label:string){const root=svg('svg',{viewBox:'0 0 24 24','aria-hidden':'true',width:18,height:18,fill:'none',stroke:'currentColor','stroke-width':2,'stroke-linecap':'round','stroke-linejoin':'round'});node.forEach(([tag,attrs])=>root.append(svg(tag,attrs)));const wrap=dom('span','icon');wrap.title=label;wrap.append(root);return wrap}
function iconButton(id:string,label:string,node:IconNode){const button=dom('button','icon-button') as HTMLButtonElement;button.id=id;button.type='button';button.setAttribute('aria-label',label);button.title=label;button.append(icon(node,label));return button}

const state={
  map:null as AnyRecord|null, topology:null as AnyRecord|null, layout:null as LayoutNode|null,
  expanded:'', selectedGroup:'', selectedNode:'', snapshotRef:'', zoom:1,
	search:'', inspectorWidth:Number(localStorage.getItem('dagrail.inspectorWidth')||328),
	view:'map' as 'map'|'execution'|'timeline'|'operations',
  viewport:null as {left:number;top:number;zoom:number;focus:string}|null,
  theme:(localStorage.getItem('dagrail.theme')||'system') as 'system'|'light'|'dark',
  navigatorPinned:localStorage.getItem('dagrail.navigatorPinned')==='true',
  controller:null as AbortController|null, detailController:null as AbortController|null,
  worker:null as Worker|null, requestID:0, busy:false, autoRefresh:Number(localStorage.getItem('dagrail.autoRefresh')||0), timer:0,
};

async function api(path:string,params?:URLSearchParams,signal?:AbortSignal){const response=await fetch(path+(params?.size?`?${params}`:''),{signal,headers:{Accept:'application/json'}});let value:AnyRecord;try{value=await response.json()}catch{throw new Error(`Explorer returned ${response.status}`)}if(!response.ok)throw new Error(value.error||`Explorer returned ${response.status}`);return value}
function setBusy(value:boolean,message=''){state.busy=value;document.body.classList.toggle('busy',value);$('progress').toggleAttribute('hidden',!value);$('progress-label').textContent=message||'Updating view';}
function showError(error:unknown){$('error').textContent=error instanceof Error?error.message:String(error);$('error').hidden=false;$('connection').dataset.state='disconnected';$('connection').textContent='Disconnected';}
function clearError(){$('error').hidden=true;$('error').textContent='';$('connection').dataset.state='connected';$('connection').textContent='Connected';}

function snapshotParams(){const params=new URLSearchParams();if(state.expanded)params.append('expanded',state.expanded);if(state.snapshotRef)params.set('snapshotRef',state.snapshotRef);params.set('groupState','collapsed');return params}

async function loadProject(force=false,autoCenter=true){state.controller?.abort();const controller=new AbortController();state.controller=controller;setBusy(true,force?'Refreshing verified snapshot':'Loading project map');
  try{
    const params=new URLSearchParams();if(force)params.set('refresh','1');
    const projectMap=await api('/api/v1/project-map',params,controller.signal);
    if(controller!==state.controller)return;
    state.map=projectMap;state.snapshotRef=projectMap.snapshotRef;$('project-name').textContent=projectMap.project.name||'DAG project';$('revision').textContent=`#${projectMap.headSequence} · ${short(projectMap.graphRevision)}`;
    if(state.expanded)state.topology=await loadGroupTopology(state.expanded,projectMap,controller.signal);else state.topology=projectMapToTopology(projectMap);
    renderNavigator();await renderGraph(autoCenter);renderInspector();if(state.search)locate(state.search);clearError();writeURL();
  }catch(error){if((error as Error).name!=='AbortError')showError(error)}finally{if(controller===state.controller){state.controller=null;setBusy(false);scheduleRefresh();}}
}

function projectMapToTopology(map:AnyRecord){return {groups:map.groups,nodes:map.nodes,lanes:map.lanes,aggregateEdges:map.aggregateEdges,backboneEdges:map.aggregateEdges,aggregateEdgePage:map.aggregateEdgePage,aggregateEdgeIndexRef:map.aggregateEdgeIndexRef,headSequence:map.headSequence,graphRevision:map.graphRevision}}
async function loadGroupTopology(groupID:string,projectMap:AnyRecord,signal:AbortSignal){
  const nodes=new Map((projectMap.nodes||[]).map((node:AnyRecord)=>[node.id,node]));
  const groups=new Map((projectMap.groups||[]).map((group:AnyRecord)=>[group.id,group]));
  let cursor=0,combined:AnyRecord|null=null;
  do{
    const params=new URLSearchParams({id:groupID,cursor:String(cursor),limit:'200',snapshotRef:projectMap.snapshotRef});
    const members=await api('/api/v1/group-members',params,signal);
    if(members.snapshotRef!==projectMap.snapshotRef)throw new Error('Project changed while expanding the group');
    const page=members.topology;for(const node of page.nodes||[])nodes.set(node.id,node);for(const group of page.groups||[])groups.set(group.id,group);
    if(!combined)combined={...page};
    if(page.page.nextCursor===undefined)break;
    cursor=page.page.nextCursor;
  }while(true);
  if(!combined)throw new Error('Group members are unavailable');
  combined.nodes=[...nodes.values()];combined.groups=[...groups.values()];combined.backboneEdges=combined.aggregateEdges||[];
  return combined;
}
async function neighborhoodEdges(topology:AnyRecord,focus:string,signal?:AbortSignal){const base=topology.backboneEdges||topology.aggregateEdges||[];if(!focus||!topology.aggregateEdgeIndexRef)return base;const result=new Map(base.map((edge:AnyRecord)=>[edge.edgeDigest,edge]));let cursor=0;do{const params=snapshotParams();params.set('ref',topology.aggregateEdgeIndexRef);params.set('focus',focus);params.set('cursor',String(cursor));params.set('limit','100');const next=await api('/api/v1/aggregate-edges',params,signal);if(next.headSequence!==topology.headSequence)throw new Error('Topology changed while loading dependency edges');next.aggregateEdges.forEach((edge:AnyRecord)=>result.set(edge.edgeDigest,edge));if(next.page.nextCursor===undefined)break;cursor=next.page.nextCursor}while(true);return [...result.values()]}

function visibleTopology(){const topology=state.topology||projectMapToTopology(state.map||{});const groups=(topology.groups||[]).filter((group:AnyRecord)=>group.visible);const nodes=topology.nodes||[];return {groups,nodes,edges:topology.aggregateEdges||[],lanes:topology.lanes||[]}}
function refID(ref:string){return ref.replace(/^(group|node):/,'')}
function byID(a:AnyRecord,b:AnyRecord){return String(a.id).localeCompare(String(b.id))}
function elkNodeForGroup(group:AnyRecord,groups:AnyRecord[],nodes:AnyRecord[]):AnyRecord{const children:AnyRecord[]=[];for(const child of groups.filter(value=>value.parentGroupId===group.id).sort(byID))children.push(elkNodeForGroup(child,groups,nodes));for(const node of nodes.filter(value=>value.groupId===group.id).sort(byID))children.push({id:node.id,width:142,height:52});const base:AnyRecord={id:group.id,width:168,height:76};if(children.length){base.children=children;base.layoutOptions={'elk.padding':'[top=46,left=18,bottom=18,right=18]','elk.spacing.nodeNode':'24','elk.direction':'DOWN'};}return base}
function buildELKGraph(data:{groups:AnyRecord[];nodes:AnyRecord[];edges:AnyRecord[]}){const groupIDs=new Set(data.groups.map(group=>group.id));const nodeIDs=new Set(data.nodes.map(node=>node.id));const children:AnyRecord[]=[];for(const group of data.groups.filter(value=>!value.parentGroupId||!groupIDs.has(value.parentGroupId)).sort(byID))children.push(elkNodeForGroup(group,data.groups,data.nodes));for(const node of data.nodes.filter(value=>!value.groupId||!groupIDs.has(value.groupId)).sort(byID))children.push({id:node.id,width:142,height:52});const available=new Set([...groupIDs,...nodeIDs]);const edges=data.edges.map((edge,index)=>({id:edge.edgeDigest||`edge-${index}`,sources:[refID(edge.fromRef)],targets:[refID(edge.toRef)]})).filter(edge=>available.has(edge.sources[0])&&available.has(edge.targets[0])&&edge.sources[0]!==edge.targets[0]).sort(byID);return {id:'root',children,edges,layoutOptions:{'elk.algorithm':'layered','elk.direction':'DOWN','elk.edgeRouting':'ORTHOGONAL','elk.layered.spacing.nodeNodeBetweenLayers':'92','elk.spacing.nodeNode':'42','elk.layered.crossingMinimization.strategy':'LAYER_SWEEP','elk.layered.considerModelOrder.strategy':'NODES_AND_EDGES','elk.layered.crossingMinimization.forceNodeModelOrder':'true','elk.layered.nodePlacement.strategy':'BRANDES_KOEPF','elk.padding':'[top=44,left=44,bottom=44,right=44]'}}}

function layoutGraph(graph:AnyRecord){state.worker?.terminate();const worker=new Worker('/assets/layout-worker.js');state.worker=worker;const requestID=++state.requestID,registerID=requestID*2,layoutID=registerID+1;return new Promise<LayoutNode>((resolve,reject)=>{worker.addEventListener('message',event=>{if(event.data.id===registerID){if(event.data.error){reject(new Error(String(event.data.error)));return}worker.postMessage({id:layoutID,cmd:'layout',graph,layoutOptions:{},options:{logging:false,measureExecutionTime:false}});return}if(event.data.id!==layoutID)return;event.data.error?reject(new Error(String(event.data.error))):resolve(event.data.data)});worker.addEventListener('error',event=>reject(new Error(event.message||'Layout worker failed')),{once:true});worker.postMessage({id:registerID,cmd:'register',algorithms:['layered']});});}

async function renderGraph(autoCenter=false){if(!state.topology)return;const topology=state.topology;if(!topology.backboneEdges)topology.backboneEdges=topology.aggregateEdges||[];topology.aggregateEdges=await neighborhoodEdges(topology,state.selectedGroup||state.selectedNode,state.controller?.signal);const data=visibleTopology();const layout=await layoutGraph(buildELKGraph(data));state.layout=layout;const graph=$<SVGSVGElement>('graph');graph.replaceChildren();graph.setAttribute('width',String(Math.max(1,layout.width||1)*state.zoom));graph.setAttribute('height',String(Math.max(1,layout.height||1)*state.zoom));graph.setAttribute('viewBox',`0 0 ${layout.width||1} ${layout.height||1}`);graph.dataset.zoom=String(state.zoom);
  const edgeLayer=svg('g',{class:'edge-layer'}),nodeLayer=svg('g',{class:'node-layer'});graph.append(edgeLayer,nodeLayer);renderEdges(layout,edgeLayer,data);renderNodes(layout,nodeLayer,data,0,0);renderMinimap(layout,data);
  if(autoCenter){requestAnimationFrame(()=>{if(state.expanded)centerRef(state.expanded,true);else fitView();});}
}

function flatten(node:LayoutNode,offsetX=0,offsetY=0,result=new Map<string,{node:LayoutNode;x:number;y:number}>()){const x=offsetX+(node.x||0),y=offsetY+(node.y||0);result.set(node.id,{node,x,y});for(const child of node.children||[])flatten(child,x,y,result);return result}
function renderEdges(layout:LayoutNode,layer:SVGElement,data:ReturnType<typeof visibleTopology>){const positions=flatten(layout),routes=new Map((layout.edges||[]).map(edge=>[edge.id,edge]));const selected=state.selectedGroup||state.selectedNode;const neighbors=new Set<string>(selected?[selected]:[]);for(const edge of data.edges){const from=refID(edge.fromRef),to=refID(edge.toRef);if(from===selected||to===selected){neighbors.add(from);neighbors.add(to)}}for(let index=0;index<data.edges.length;index++){const edge=data.edges[index],fromID=refID(edge.fromRef),toID=refID(edge.toRef),from=positions.get(fromID),to=positions.get(toID);if(!from||!to)continue;const route=routes.get(edge.edgeDigest||`edge-${index}`),section=route?.sections?.[0];let d='',labelX=0,labelY=0;if(section){const points=[section.startPoint,...(section.bendPoints||[]),section.endPoint];d=points.map((point,i)=>`${i?'L':'M'} ${point.x} ${point.y}`).join(' ');const middle=points[Math.floor(points.length/2)];labelX=middle.x+5;labelY=middle.y-5}else{const x1=from.x+(from.node.width||0)/2,y1=from.y+(from.node.height||0),x2=to.x+(to.node.width||0)/2,y2=to.y,mid=y1+(y2-y1)/2;d=`M ${x1} ${y1} L ${x1} ${mid} L ${x2} ${mid} L ${x2} ${y2}`;labelX=(x1+x2)/2+5;labelY=mid-5}const path=svg('path',{d,class:`dag-edge${selected&&!(neighbors.has(fromID)&&neighbors.has(toID))?' muted':''}`});path.dataset.from=fromID;path.dataset.to=toID;layer.append(path);if(edge.count>1){const label=svg('text',{x:labelX,y:labelY,class:'edge-label'});label.textContent=`×${edge.count}`;layer.append(label)}}}
function renderNodes(layout:LayoutNode,layer:SVGElement,data:ReturnType<typeof visibleTopology>,ox:number,oy:number){const groups=new Map(data.groups.map((group:AnyRecord)=>[group.id,group]));const nodes=new Map(data.nodes.map((node:AnyRecord)=>[node.id,node]));const selected=state.selectedGroup||state.selectedNode;const neighborIDs=new Set<string>(selected?[selected]:[]);for(const edge of data.edges){const from=refID(edge.fromRef),to=refID(edge.toRef);if(from===selected||to===selected){neighborIDs.add(from);neighborIDs.add(to)}}for(const item of layout.children||[]){const x=ox+(item.x||0),y=oy+(item.y||0);const group=groups.get(item.id),node=nodes.get(item.id);if(group)layer.append(renderGroup(item,group,x,y,selected,neighborIDs));else if(node)layer.append(renderNode(item,node,x,y,selected,neighborIDs));if(item.children?.length)renderNodes(item,layer,data,x,y)}}
function renderGroup(item:LayoutNode,group:AnyRecord,x:number,y:number,selected:string,neighbors:Set<string>){const root=svg('g',{class:`dag-group status-${safeClass(group.displayStatus)}${state.expanded===group.id?' expanded':''}${selected===group.id?' selected':''}${selected&&!neighbors.has(group.id)?' spotlight-muted':''}`,transform:`translate(${x},${y})`,tabindex:0,role:'button','aria-expanded':state.expanded===group.id?'true':'false','aria-label':`${group.id}, ${group.displayStatus}, ${group.nodeCount} nodes`});root.dataset.ref=group.id;const rect=svg('rect',{width:item.width||168,height:item.height||76,rx:12});const title=svg('text',{x:16,y:28,class:'node-id'});title.textContent=group.id;const status=svg('text',{x:16,y:51,class:'node-status'});status.textContent=`${group.displayStatus} · ${group.nodeCount} nodes`;const action=svg('g',{class:'expand-glyph',transform:`translate(${(item.width||168)-34},16)`});action.append(iconSVG(state.expanded===group.id?Minimize2:Maximize2));root.append(rect,title,status,action);const full=svg('title');full.textContent=`${group.title} — ${group.displayStatus}`;root.append(full);root.addEventListener('click',event=>{event.stopPropagation();toggleGroup(group.id)});root.addEventListener('keydown',event=>{if((event as KeyboardEvent).key==='Enter'||(event as KeyboardEvent).key===' '){event.preventDefault();toggleGroup(group.id)}});return root}
function renderNode(item:LayoutNode,node:AnyRecord,x:number,y:number,selected:string,neighbors:Set<string>){const root=svg('g',{class:`dag-node status-${safeClass(node.readiness||node.status)}${selected===node.id?' selected':''}${selected&&!neighbors.has(node.id)?' spotlight-muted':''}`,transform:`translate(${x},${y})`,tabindex:0,role:'button','aria-label':`${node.id}, ${node.readiness||node.status}`});root.dataset.ref=node.id;const rect=svg('rect',{width:item.width||142,height:item.height||52,rx:9});const title=svg('text',{x:14,y:22,class:'node-id'});title.textContent=node.id;const status=svg('text',{x:14,y:40,class:'node-status'});status.textContent=node.readiness||node.status;root.append(rect,title,status);const full=svg('title');full.textContent=`${node.title} — ${node.readiness||node.status}`;root.append(full);root.addEventListener('click',event=>{event.stopPropagation();selectNode(node.id)});root.addEventListener('keydown',event=>{if((event as KeyboardEvent).key==='Enter'||(event as KeyboardEvent).key===' '){event.preventDefault();selectNode(node.id)}});return root}
function iconSVG(node:IconNode){const root=svg('svg',{viewBox:'0 0 24 24',width:18,height:18,fill:'none',stroke:'currentColor','stroke-width':2,'stroke-linecap':'round','stroke-linejoin':'round'});node.forEach(([tag,attrs])=>root.append(svg(tag,attrs)));return root}
function safeClass(value:string){return String(value||'unknown').toLowerCase().replace(/[^a-z0-9-]/g,'-')}

async function toggleGroup(groupID:string){if(state.busy)return;if(state.expanded===groupID){collapseGroup();return}const scroll=$('canvas-scroll');if(!state.viewport)state.viewport={left:scroll.scrollLeft,top:scroll.scrollTop,zoom:state.zoom,focus:state.selectedGroup||state.selectedNode};state.expanded=groupID;state.selectedGroup=groupID;state.selectedNode='';writeURL();await loadProject(false)}
async function collapseGroup(){const prior=state.viewport;state.expanded='';state.selectedGroup='';writeURL();await loadProject(false);if(prior){state.zoom=prior.zoom;applyZoom();requestAnimationFrame(()=>{$('canvas-scroll').scrollTo({left:prior.left,top:prior.top,behavior:reducedMotion()?'auto':'smooth'});if(prior.focus)focusRef(prior.focus)});}state.viewport=null}
function centerRef(id:string,fit=false){const target=document.querySelector<SVGGElement>(`[data-ref="${CSS.escape(id)}"]`);if(!target)return;const box=target.getBBox(),scroll=$('canvas-scroll');if(fit&&state.expanded===id){const proposed=Math.min(1.15,Math.max(.48,Math.min((scroll.clientWidth-96)/(box.width+240),(scroll.clientHeight-96)/(box.height+180))));state.zoom=proposed;applyZoom();}const bounds=target.getBoundingClientRect(),host=scroll.getBoundingClientRect();scroll.scrollBy({left:bounds.left-host.left+bounds.width/2-host.width/2,top:bounds.top-host.top+bounds.height/2-host.height/2,behavior:reducedMotion()?'auto':'smooth'});focusRef(id)}
function focusRef(id:string){document.querySelector<SVGGElement>(`[data-ref="${CSS.escape(id)}"]`)?.focus({preventScroll:true})}
function fitView(){if(!state.layout)return;const scroll=$('canvas-scroll');state.zoom=Math.min(1,Math.max(.32,Math.min((scroll.clientWidth-48)/(state.layout.width||1),(scroll.clientHeight-48)/(state.layout.height||1))));applyZoom();scroll.scrollTo({left:0,top:0,behavior:reducedMotion()?'auto':'smooth'});}
function applyZoom(){const graph=$<SVGSVGElement>('graph');if(!state.layout)return;graph.setAttribute('width',String((state.layout.width||1)*state.zoom));graph.setAttribute('height',String((state.layout.height||1)*state.zoom));$('zoom-value').textContent=`${Math.round(state.zoom*100)}%`;renderMinimap(state.layout,visibleTopology())}

function renderNavigator(){const groups=(state.map?.groups||[]) as AnyRecord[];const byParent=new Map<string,AnyRecord[]>();groups.forEach(group=>{const parent=group.parentGroupId||'';byParent.set(parent,[...(byParent.get(parent)||[]),group])});byParent.forEach(items=>items.sort((a,b)=>a.id.localeCompare(b.id)));const root=$('tree');root.replaceChildren();const branch=(parent:string,depth:number)=>{for(const group of byParent.get(parent)||[]){const row=dom('button',`tree-row${state.selectedGroup===group.id?' selected':''}`) as HTMLButtonElement;row.type='button';row.style.setProperty('--depth',String(depth));row.title=group.title;row.append(icon(ChevronRight,'Open group'),dom('span','tree-id',group.id),dom('span',`status-dot status-${safeClass(group.displayStatus)}`));row.addEventListener('click',()=>toggleGroup(group.id));root.append(row);branch(group.id,depth+1)}};branch('',0);$('navigator').classList.toggle('open',state.navigatorPinned);$('navigator').classList.toggle('pinned',state.navigatorPinned);document.body.classList.toggle('navigator-pinned',state.navigatorPinned);const label=state.navigatorPinned?'Unpin navigator':'Open and pin navigator';$('navigator-pin').replaceChildren(icon(state.navigatorPinned?PinOff:Pin,label));$('navigator-pin').setAttribute('aria-label',label);$('navigator-pin').title=label;}
let searchTimer=0;async function locate(query:string){clearTimeout(searchTimer);searchTimer=window.setTimeout(async()=>{const root=$('search-results');if(!query.trim()){root.replaceChildren();return}try{const result=await api('/api/v1/locate',new URLSearchParams({q:query.trim(),limit:'30'}));if(result.snapshotRef!==state.snapshotRef)return;root.replaceChildren(...result.results.map((item:AnyRecord)=>{const button=dom('button','search-result') as HTMLButtonElement;button.type='button';button.append(dom('strong','',item.id),dom('span','',item.title),dom('small','',item.ancestorPath.join(' / ')));button.addEventListener('click',()=>item.kind==='group'?toggleGroup(item.id):selectLocatedNode(item));return button}));}catch(error){showError(error)}},220)}
async function selectLocatedNode(item:AnyRecord){const parent=item.ancestorPath.at(-1)||'';if(parent&&state.expanded!==parent){state.selectedNode='';state.selectedGroup='';state.expanded=parent;writeURL();await loadProject(false,false)}selectNode(item.id)}

async function selectNode(id:string){state.selectedNode=id;state.selectedGroup='';writeURL();renderInspectorSkeleton(id);updateSpotlight();centerRef(id,false);state.detailController?.abort();const controller=new AbortController();state.detailController=controller;void refreshSpotlightEdges(controller.signal);try{const detail=await api('/api/v1/node',new URLSearchParams({id}),controller.signal);if(detail.headSequence!==state.map?.headSequence)throw new Error('Node detail belongs to a stale snapshot');renderNodeDetail(detail);centerRef(id,false)}catch(error){if((error as Error).name!=='AbortError')showError(error)}}
async function refreshSpotlightEdges(signal?:AbortSignal){if(!state.topology||!state.layout)return;state.topology.aggregateEdges=await neighborhoodEdges(state.topology,state.selectedGroup||state.selectedNode,signal);const graph=$<SVGSVGElement>('graph'),old=graph.querySelector('.edge-layer');if(!old)return;const layer=svg('g',{class:'edge-layer'});old.replaceWith(layer);renderEdges(state.layout,layer,visibleTopology());updateSpotlight()}
function restoreBackboneEdges(){if(!state.topology||!state.layout)return;state.topology.aggregateEdges=state.topology.backboneEdges||state.topology.aggregateEdges;const old=$<SVGSVGElement>('graph').querySelector('.edge-layer');if(!old)return;const layer=svg('g',{class:'edge-layer'});old.replaceWith(layer);renderEdges(state.layout,layer,visibleTopology());updateSpotlight()}
function updateSpotlight(){
  const selected=state.selectedGroup||state.selectedNode,neighbors=new Set<string>(selected?[selected]:[]);
  document.querySelectorAll<SVGPathElement>('.dag-edge').forEach(edge=>{if(edge.dataset.from===selected||edge.dataset.to===selected){neighbors.add(edge.dataset.from||'');neighbors.add(edge.dataset.to||'')}});
  document.querySelectorAll<SVGGElement>('[data-ref]').forEach(item=>{item.classList.toggle('selected',item.dataset.ref===selected);item.classList.toggle('spotlight-muted',Boolean(selected&&!neighbors.has(item.dataset.ref||'')))});
  document.querySelectorAll<SVGPathElement>('.dag-edge').forEach(edge=>edge.classList.toggle('muted',Boolean(selected&&!(neighbors.has(edge.dataset.from||'')&&neighbors.has(edge.dataset.to||'')))));
}
function renderInspector(){if(state.selectedNode)return;if(state.selectedGroup){const group=(state.map?.groups||[]).find((value:AnyRecord)=>value.id===state.selectedGroup);if(group)renderGroupDetail(group);return}$('inspector').classList.remove('open');$('inspector-content').replaceChildren();}
function renderInspectorSkeleton(id:string){$('inspector').classList.add('open');$('inspector-title').textContent=id;$('inspector-content').replaceChildren(dom('div','skeleton','Loading node details…'))}
function definitionList(rows:Array<[string,unknown]>){const list=dom('dl','detail-list');rows.forEach(([key,value])=>{list.append(dom('dt','',key),dom('dd','',value===undefined||value===null||value===''?'—':String(value)))});return list}
function renderGroupDetail(group:AnyRecord){$('inspector').classList.add('open');$('inspector-title').textContent=group.id;$('inspector-content').replaceChildren(section('Summary',definitionList([['Title',group.title],['Lifecycle',group.lifecycleStatus],['Health',group.healthStatus],['Display',group.displayStatus],['Nodes',group.nodeCount],['Ready',group.readyNodeCount],['Active attempts',group.activeAttemptCount],['Open incidents',group.openIncidentCount],['Uncertain effects',group.uncertainEffectCount],['Unclosed resources',group.unclosedResourceCount]])))}
function renderNodeDetail(detail:AnyRecord){const node=detail.contract;$('inspector').classList.add('open');$('inspector-title').textContent=node.id;const content=$('inspector-content');content.replaceChildren(section('Contract',definitionList([['Title',node.title],['Kind',node.kind],['Role',node.role],['Group',node.groupId],['Objective',node.objective],['Outcomes',(node.outcomes||[]).map((v:AnyRecord)=>`${v.id} · ${v.class}`).join(', ')]])),section('Runtime',definitionList([['Status',detail.runtime.status],['Readiness',detail.readiness?.state],['Outcome',detail.runtime.outcome],['Attempts',detail.counts.attempts],['Incidents',detail.counts.incidents],['Effects',detail.counts.effects],['Resources',detail.counts.resources]])),section('Dependencies',definitionList([['Incoming',detail.counts.incoming],['Outgoing',detail.counts.outgoing],['Blockers',(detail.readiness?.reasons||[]).map((v:AnyRecord)=>v.code).join(', ')]])))}
function section(title:string,content:HTMLElement){const root=dom('section','inspector-section');root.append(dom('h3','',title),content);return root}

async function switchView(view:'map'|'execution'|'timeline'|'operations'){
  state.view=view;document.querySelectorAll<HTMLButtonElement>('[data-explorer-view]').forEach(button=>button.setAttribute('aria-selected',String(button.dataset.explorerView===view)));
  const mapVisible=view==='map';$('canvas-scroll').hidden=!mapVisible;$('audit-view').hidden=mapVisible;writeURL();if(mapVisible)return;
  const audit=$('audit-view');audit.replaceChildren(dom('div','skeleton',`Loading ${view}…`));
  try{let payload:AnyRecord;if(view==='execution')payload=await api('/api/v1/topology',new URLSearchParams({mode:'detail',limit:'500'}));else if(view==='timeline')payload=await api('/api/v1/history',new URLSearchParams({limit:'100'}));else payload=await api('/api/v1/operations',new URLSearchParams({limit:'200'}));renderAudit(view,payload)}catch(error){audit.replaceChildren(dom('div','error-card',error instanceof Error?error.message:String(error)))}
}
function renderAudit(view:string,payload:AnyRecord){const audit=$('audit-view');const heading=dom('div','audit-heading');heading.append(dom('span','eyebrow',view==='execution'?'Execution detail':view==='timeline'?'Timeline':'Operations'),dom('strong','',`Snapshot #${payload.headSequence??state.map?.headSequence??'—'}`));const pre=dom('pre','audit-json');pre.textContent=JSON.stringify(payload,null,2);audit.replaceChildren(heading,pre)}

function renderMinimap(layout:LayoutNode,data:ReturnType<typeof visibleTopology>){const mini=$<SVGSVGElement>('minimap');mini.replaceChildren();mini.setAttribute('viewBox',`0 0 ${layout.width||1} ${layout.height||1}`);const positions=flatten(layout);for(const edge of data.edges){const from=positions.get(refID(edge.fromRef)),to=positions.get(refID(edge.toRef));if(!from||!to)continue;mini.append(svg('line',{x1:from.x+(from.node.width||0)/2,y1:from.y+(from.node.height||0)/2,x2:to.x+(to.node.width||0)/2,y2:to.y+(to.node.height||0)/2,class:'mini-edge'}))}for(const {node,x,y} of positions.values()){if(node.id==='root')continue;mini.append(svg('rect',{x,y,width:node.width||10,height:node.height||10,rx:3,class:'mini-node'}))}updateViewportBox()}
function updateViewportBox(){if(!state.layout)return;const mini=$<SVGSVGElement>('minimap');mini.querySelector('.mini-viewport')?.remove();const scroll=$('canvas-scroll'),scale=state.zoom;mini.append(svg('rect',{x:scroll.scrollLeft/scale,y:scroll.scrollTop/scale,width:scroll.clientWidth/scale,height:scroll.clientHeight/scale,class:'mini-viewport'}))}
function navigateMinimap(event:MouseEvent){if(!state.layout)return;const rect=$('minimap').getBoundingClientRect(),x=(event.clientX-rect.left)/rect.width*(state.layout.width||1),y=(event.clientY-rect.top)/rect.height*(state.layout.height||1),scroll=$('canvas-scroll');scroll.scrollTo({left:x*state.zoom-scroll.clientWidth/2,top:y*state.zoom-scroll.clientHeight/2,behavior:reducedMotion()?'auto':'smooth'})}

function short(value:string){return value?value.slice(0,10):'uninitialized'}
function reducedMotion(){return matchMedia('(prefers-reduced-motion: reduce)').matches}
function setTheme(theme:'system'|'light'|'dark'){state.theme=theme;localStorage.setItem('dagrail.theme',theme);document.documentElement.dataset.theme=theme;resolveTheme();const next=theme==='system'?'light':theme==='light'?'dark':'system';const glyph=theme==='light'?Sun:theme==='dark'?Moon:Monitor;const label=`Theme: ${theme}. Switch to ${next}`;$('theme').replaceChildren(icon(glyph,label));$('theme').setAttribute('aria-label',label);$('theme').title=label}
function cycleTheme(){setTheme(state.theme==='system'?'light':state.theme==='light'?'dark':'system')}
function resolveTheme(){const dark=state.theme==='dark'||(state.theme==='system'&&matchMedia('(prefers-color-scheme: dark)').matches);document.documentElement.dataset.resolvedTheme=dark?'dark':'light'}
function writeURL(){const params=new URLSearchParams();if(state.view!=='map')params.set('view',state.view);if(state.expanded)params.set('group',state.expanded);if(state.selectedNode)params.set('node',state.selectedNode);if(state.search)params.set('q',state.search);history.replaceState({},'',location.pathname+(params.size?`?${params}`:''))}
function readURL(){const params=new URLSearchParams(location.search);const view=params.get('view');state.view=view==='execution'||view==='timeline'||view==='operations'?view:'map';state.expanded=params.get('group')||'';state.selectedGroup=state.expanded;state.selectedNode=params.get('node')||'';state.search=params.get('q')||''}
function scheduleRefresh(){clearTimeout(state.timer);if(!state.autoRefresh)return;state.timer=window.setTimeout(pollHead,state.autoRefresh*1000)}
async function pollHead(){const active=document.activeElement;if(state.busy||state.selectedNode||state.selectedGroup||document.hidden||active instanceof HTMLInputElement||active instanceof HTMLTextAreaElement){scheduleRefresh();return}try{const head=await api('/api/v1/head');if(head.changed)await loadProject(true);else{clearError();scheduleRefresh()}}catch(error){showError(error);scheduleRefresh()}}

function installChrome(){const tools=$('canvas-tools'),zoom=dom('span','zoom-value','100%');zoom.id='zoom-value';const refreshRate=dom('select','refresh-rate') as HTMLSelectElement;refreshRate.id='auto-refresh';refreshRate.setAttribute('aria-label','Automatic refresh interval');refreshRate.title='Automatic refresh interval';for(const [value,label] of [['0','Auto off'],['30','Auto 30s'],['60','Auto 60s']]){const option=dom('option','',label) as HTMLOptionElement;option.value=value;refreshRate.append(option)}refreshRate.value=String(state.autoRefresh);tools.append(iconButton('refresh','Refresh project map',RefreshCw),refreshRate,iconButton('fit','Fit project map',Focus),iconButton('locate-selected','Center selected',LocateFixed),iconButton('zoom-out','Zoom out',ZoomOut),zoom,iconButton('zoom-in','Zoom in',ZoomIn));$('navigator-toggle').replaceChildren(icon(PanelLeft,'Toggle navigator'));$('navigator-pin').replaceChildren(icon(state.navigatorPinned?PinOff:Pin,state.navigatorPinned?'Unpin navigator':'Pin navigator'));$('theme').replaceChildren(icon(Moon,'Toggle theme'));$('inspector-close').replaceChildren(icon(X,'Close inspector'));}

installChrome();readURL();setTheme(state.theme);document.documentElement.style.setProperty('--inspector',`${Math.min(560,Math.max(280,state.inspectorWidth))}px`);$<HTMLInputElement>('search').value=state.search;if(state.search)locate(state.search);
$('refresh').addEventListener('click',()=>loadProject(true));$('auto-refresh').addEventListener('change',event=>{state.autoRefresh=Number((event.target as HTMLSelectElement).value);localStorage.setItem('dagrail.autoRefresh',String(state.autoRefresh));scheduleRefresh()});$('fit').addEventListener('click',fitView);$('locate-selected').addEventListener('click',()=>centerRef(state.selectedGroup||state.selectedNode,true));$('zoom-in').addEventListener('click',()=>{state.zoom=Math.min(1.8,state.zoom+.15);applyZoom()});$('zoom-out').addEventListener('click',()=>{state.zoom=Math.max(.3,state.zoom-.15);applyZoom()});
document.querySelectorAll<HTMLButtonElement>('[data-explorer-view]').forEach(button=>button.addEventListener('click',()=>switchView(button.dataset.explorerView as typeof state.view)));
$('navigator-toggle').addEventListener('click',()=>$('navigator').classList.toggle('open'));$('navigator-pin').addEventListener('click',()=>{state.navigatorPinned=!state.navigatorPinned;localStorage.setItem('dagrail.navigatorPinned',String(state.navigatorPinned));renderNavigator()});$('theme').addEventListener('click',cycleTheme);$('search').addEventListener('input',event=>{state.search=(event.target as HTMLInputElement).value;writeURL();locate(state.search)});
$('inspector-close').addEventListener('click',()=>{state.selectedNode='';state.selectedGroup=state.expanded;renderInspector();restoreBackboneEdges();writeURL()});$('canvas-scroll').addEventListener('scroll',updateViewportBox,{passive:true});$('minimap').addEventListener('click',event=>navigateMinimap(event as MouseEvent));
$('minimap').addEventListener('keydown',event=>{if((event as KeyboardEvent).key==='Enter'||(event as KeyboardEvent).key===' '){event.preventDefault();fitView()}});
{const handle=$('inspector-resizer');let resizing=false;const resize=(clientX:number)=>{state.inspectorWidth=Math.min(560,Math.max(280,window.innerWidth-clientX));document.documentElement.style.setProperty('--inspector',`${state.inspectorWidth}px`);localStorage.setItem('dagrail.inspectorWidth',String(state.inspectorWidth));};handle.addEventListener('pointerdown',event=>{resizing=true;handle.setPointerCapture(event.pointerId)});handle.addEventListener('pointermove',event=>{if(resizing)resize(event.clientX)});const stop=(event:PointerEvent)=>{if(!resizing)return;resizing=false;handle.releasePointerCapture(event.pointerId)};handle.addEventListener('pointerup',stop);handle.addEventListener('pointercancel',stop);handle.addEventListener('keydown',event=>{if(event.key==='ArrowLeft'||event.key==='ArrowRight'){event.preventDefault();state.inspectorWidth=Math.min(560,Math.max(280,state.inspectorWidth+(event.key==='ArrowLeft'?16:-16)));document.documentElement.style.setProperty('--inspector',`${state.inspectorWidth}px`);localStorage.setItem('dagrail.inspectorWidth',String(state.inspectorWidth));}})}
{const canvas=$('canvas-scroll');let dragging=false,startX=0,startY=0,startLeft=0,startTop=0;canvas.addEventListener('pointerdown',event=>{const target=event.target as Element;if(target.closest('[data-ref]')&&event.button===0)return;if(event.button!==0&&event.button!==1)return;dragging=true;startX=event.clientX;startY=event.clientY;startLeft=canvas.scrollLeft;startTop=canvas.scrollTop;canvas.setPointerCapture(event.pointerId);canvas.classList.add('grabbing')});canvas.addEventListener('pointermove',event=>{if(!dragging)return;canvas.scrollLeft=startLeft-(event.clientX-startX);canvas.scrollTop=startTop-(event.clientY-startY)});const stop=(event:PointerEvent)=>{if(!dragging)return;dragging=false;canvas.releasePointerCapture(event.pointerId);canvas.classList.remove('grabbing')};canvas.addEventListener('pointerup',stop);canvas.addEventListener('pointercancel',stop)}
document.addEventListener('keydown',event=>{if(event.key==='Escape'){if(state.selectedNode){state.selectedNode='';state.selectedGroup=state.expanded;renderInspector();restoreBackboneEdges();writeURL()}else if(state.expanded)collapseGroup();}});matchMedia('(prefers-color-scheme: dark)').addEventListener('change',()=>{if(state.theme==='system')resolveTheme()});window.addEventListener('resize',()=>{updateViewportBox()});
window.addEventListener('popstate',()=>{state.controller?.abort();readURL();$<HTMLInputElement>('search').value=state.search;void loadProject(false);if(state.search)locate(state.search)});
loadProject(false).then(()=>{if(state.view!=='map')switchView(state.view)});
